config/routes.rb
class AdminConstraint
  def matches?(request)
    return false unless request.session[:user_id]
    user = User.find request.session[:user_id]
    user && user.admin?
  end
end

require 'sidekiq/web'
Submify::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

  resources :password_resets
  resources :votes, only: [:create, :destroy]
  resources :downvotes, only: [:create, :destroy]
  resources :topics, only: [:create, :destroy, :show, :edit ]
  resources :flags, only: [:create, :destroy]
  resources :links, only: [:create, :destroy, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :topic_user_relationships, only: [:create, :destroy]
  resources :links do
    resources :comments, only: [:create, :destroy, :show]
  end
  resources :links do
    member do
      post 'submit', 'unsubmit'
    end
  end
  resources :comments do
    resources :comments, only: [:create, :destroy, :show]
  end
  resources :topics do
    member do
      get :followers, :hovercard
    end
  end
  resources :users do
    member do
      get :following, :followers, :commented, :followed_topics, :hovercard, :notifications
    end
  end
  post 'facebook_create', to: 'users#facebook_create'
  post 'send_again', to: 'sessions#send_again'
  get 'confirmation', to: 'users#confirmation'
  get 'faq', to: 'static_pages#faq'
  match '/admin', to: 'admin#links'
  match '/admin/comments', to: 'admin#comments'
  match '/admin/topics', to: 'admin#topics'
  match '/contact', to: 'static_pages#contact'
  match '/front', to: 'static_pages#front_page'
  match '/auth/:provider/callback', to: 'sessions#fb'
  match '/auth/failure', to: 'sessions#failure'
  match '/signup', to: 'users#new'
  match 'privacy', to: 'static_pages#privacy'
  match 'show_signup', to: 'sessions#show_signup'
  match 'show_signin', to: 'sessions#show_signin'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/autocomplete', to: 'static_pages#autocomplete', as: 'autocomplete'

  match '/autocomplete_topic', to: 'static_pages#autocomplete_topic_name', as: 'autocomplete_topic'
  root to: 'static_pages#home'

end

app/models/link_user.rb
# == Schema Information
#
# Table name: link_users
#
#  id          :integer          not null, primary key
#  link_id     :integer
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  topic_id    :integer
#  score       :integer
#  votes_count :integer          default(0)
#

#
# Submify - Dashboard of web and web activity
# Copyright (C) 2013 Vysakh Sreenivasan <support@submify.com>
#
# This file is part of Submify.
#
# Submify is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Submify is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Submify.  If not, see <http://www.gnu.org/licenses/>.
#
class LinkUser < ApplicationModel

  attr_accessible :link_id, :user_id, :topic_id

  belongs_to :link, class_name: "Link", touch: true
  belongs_to :user, class_name: "User", touch: true, counter_cache: true
  belongs_to :topic, class_name: "Topic", touch: true
  has_many :votes, as: :votable, dependent: :destroy
  has_many :downvotes,as: :votable, dependent: :destroy
  has_many :notifications, as: :parent

  default_scope order: 'link_users.created_at DESC'

  validates :link_id, presence: true
  after_create :calculate_score

  def calculate_score
    self.update_column(:score, (self.created_at.to_i/60))
  end

  def self.from_users_followed_by(user)
    followed_topic_ids = "SELECT topic_id FROM topic_user_relationships WHERE user_id = :user_id"
    followed_user_ids = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
    where("topic_id IN (#{followed_topic_ids}) OR  user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id).where('link_users.score> -10').uniq
  end
end

app/views/link_users/_link_user.html.erb
<% link = link_user.link %>
<div class="container-fluid">
  <div class= "link-<%= link_user.id %> row-fluid" >
    <div class="link_contain">
      <% topic = link_user.topic %>
      <% if (link_user.user == current_user and topic) || (current_user and current_user.admin?) %>
        <span class="unsubmit">
          <%= link_to raw("<i class=\"icon-remove icon-small\"></i>"),  unsubmit_link_path(link, unsubmit: link_user, topic: topic.id), method: :post, remote: true, data: { confirm: "You sure?" }   %>
        </span>
      <% else %>
        <%= link_to raw("<i class=\"icon-remove icon-small\"></i>"), "#", class: "dummy" %>
        <!--
        -created a dummy link so that unsigned user see a good profile links which is otherwise unaligned :)
        -->
      <% end %>  
      <% cache link_user, expires_in: 5.minutes do %>
      <div class="user-profile">
        <%= image_tag (link_user.user.avatar.url(:medium)), class: 'link-user-image'  %>
        <%= link_to link_user.user.name, link_user.user, class: 'profile_hover', data: { hovercard: link_user.user.id } %>
        submitted about <%= link_to topic.name, topic_path(topic), class: 'topic_hover', data: { hovercard: topic.id } %>
      </div> 
      <div class="lu_box container-fluid">
        <div class="link_info"><%= render 'links/link_info', link: link %></div>
      <span class="timestamp">
        <%= timeago_tag link_user.created_at, :nojs => true, :limit => 10.days.ago %>
        <!--
           -<%= timing(link_user.created_at) %>
           -->
      </span>

        <span class="votes-up"> <i class="icon-caret-up icon-small"></i></span>
        <span class="votes">
          <%= (link_user.votes_count) %>
        </span>
      <% end %>
        <span class="votes-up"> <i class="icon-comment icon-small"></i></span>
        <span class="show-comments">  <%= link_to pluralize(link.comments_count, "comment"), link %></span>
        <span class="votes-up"> <i class="icon-tag icon-small"></i></span>
        <span class="show-topics">  <%= link_to pluralize(link.link_users.count, "topic"), link %></span>

      <span class="vote">
        <%= render 'votes/vote_button', votable: link_user, type: "LinkUser" %>
      </span>
      <span id="topic-downvote">
        <%= render 'downvotes/downvote_button', votable: link_user, type: "LinkUser" %>
      </span>

    </div>
    <% if comment = link_user_comment(link, link_user.user.id) %>

    <div class="comment_link_box">
      <div id="comment_link_border">
      <%= render 'comments/comment', comment: comment %>
    </div>
    </div>
  <% end %>
    </div>

  </div>
</div>
<!--
-<div class="underline"></div>
-->