config/routes.rb
class AdminConstraint
  def matches?(request)
    return false unless request.session[:user_id]
    user = User.find request.session[:user_id]
    user && user.admin?
  end
end

require 'sidekiq/web'
Submify::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

  resources :password_resets
  resources :votes, only: [:create, :destroy]
  resources :downvotes, only: [:create, :destroy]
  resources :topics, only: [:create, :destroy, :show, :edit ]
  resources :flags, only: [:create, :destroy]
  resources :links, only: [:create, :destroy, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :topic_user_relationships, only: [:create, :destroy]
  resources :links do
    resources :comments, only: [:create, :destroy, :show]
  end
  resources :links do
    member do
      post 'submit', 'unsubmit'
    end
  end
  resources :comments do
    resources :comments, only: [:create, :destroy, :show]
  end
  resources :topics do
    member do
      get :followers, :hovercard
    end
  end
  resources :users do
    member do
      get :following, :followers, :commented, :followed_topics, :hovercard, :notifications
    end
  end
  post 'facebook_create', to: 'users#facebook_create'
  post 'send_again', to: 'sessions#send_again'
  get 'confirmation', to: 'users#confirmation'
  get 'faq', to: 'static_pages#faq'
  match '/admin', to: 'admin#links'
  match '/admin/comments', to: 'admin#comments'
  match '/admin/topics', to: 'admin#topics'
  match '/contact', to: 'static_pages#contact'
  match '/front', to: 'static_pages#front_page'
  match '/auth/:provider/callback', to: 'sessions#fb'
  match '/auth/failure', to: 'sessions#failure'
  match '/signup', to: 'users#new'
  match 'privacy', to: 'static_pages#privacy'
  match 'show_signup', to: 'sessions#show_signup'
  match 'show_signin', to: 'sessions#show_signin'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/autocomplete', to: 'static_pages#autocomplete', as: 'autocomplete'

  match '/autocomplete_topic', to: 'static_pages#autocomplete_topic_name', as: 'autocomplete_topic'
  root to: 'static_pages#home'

end

app/models/topic.rb
#
# Submify - Dashboard of web and web activity
# Copyright (C) 2013 Vysakh Sreenivasan <support@submify.com>
#
# This file is part of Submify.
#
# Submify is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Submify is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Submify.  If not, see <http://www.gnu.org/licenses/>.
#
# == Schema Information
#
# Table name: topics
#
#  id                  :integer          not null, primary key
#  name                :string(255)
#  description         :text
#  slug                :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  verify              :boolean          default(FALSE)
#

class Topic < ApplicationModel
  extend FriendlyId
  friendly_id :name, use: :slugged

  attr_accessible :description, :name, :avatar
  has_attached_file :avatar, styles: { medium: "200x200>", thumb: "100x100"}, default_style: :thumb, default_url:'/images/avatar/missing_topic_thumb.png'
  validates_attachment_content_type :avatar, :content_type => /^image\/(jpg|jpeg|pjpeg|png|x-png|gif)$/, :message => 'file type is not allowed (only jpeg/png/gif images)'

  has_many :link_users, foreign_key: "topic_id", dependent: :destroy
  has_many :links, through: :link_users, source: :link

  has_many :topic_user_relationships, foreign_key: "topic_id", dependent: :destroy

  has_many :following_users, through: :topic_user_relationships, source: :user
  
  after_save :load_soulmate

  before_destroy :remove_soulmate

  #def topic_name
    #Rails.cache.fetch([:topic, id, :name]) do
      #name
    #end
  #end

  #def flush_name_cache
    #Rails.cache.delete([:topic, id, :name]) if name_changed?
  #end


  def remove_soulmate
    do_soulmate_by_operation self.class.name.downcase, :remove
    # remove_from_soulmate self.class.name.downcase
  end
  
  def load_soulmate
    do_soulmate_by_operation self.class.name.downcase, :add
    # load_into_soulmate self.class.name.downcase
  end

  def self.search(term)
    match_from_soulmate(term,self.name.downcase) 
  end

end

app/controllers/topics_controller.rb
#
# Submify - Dashboard of web and web activity
# Copyright (C) 2013 Vysakh Sreenivasan <support@submify.com>
#
# This file is part of Submify.
#
# Submify is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Submify is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Submify.  If not, see <http://www.gnu.org/licenses/>.
#
class TopicsController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :destroy]
  before_filter :check_verification, only: [:edit, :update]

  def hovercard
    @topic = Topic.find(params[:id])
    render partial: 'hovercard'
  end

  def show
    @link = current_user.links.build  if current_user
    @topic = Topic.find(params[:id])
    @users = @topic.following_users.limit(5)
    @link_users = @topic.link_users.order("score DESC").paginate(page: params[:page], per_page: params[:per_page]||15)
    respond_to do |format|
      format.html
      format.js
    end
  end
  def followers
    @topic = Topic.find(params[:id])
    @users = @topic.following_users.paginate(page: params[:page])
  end

  def edit
    @topic = Topic.find(params[:id])
  end
  def update
    if params[:verify]=="true"
      @topic.toggle!(:verify)
    end
    if @topic.update_attributes(params[:topic])
      flash.now[:success] = "Topic updated"
      redirect_to @topic
    else
      render 'edit'
    end
  end
  def index
    @topics = Topic.limit(100).paginate(page: params[:page])
  end
  def destroy
    Topic.find(params[:id]).destroy
    flash[:success] = "Topic destroyed"
    redirect_to topics_url
  end

  private

  def check_verification
    @topic = Topic.find(params[:id])
    if @topic.verify? and !(current_user.admin?)
      flash[:notice] = "The topic is closed for editing by admin"
      redirect_to @topic
    end
  end
end

app/helpers/topics_helper.rb
#
# Submify - Dashboard of web and web activity
# Copyright (C) 2013 Vysakh Sreenivasan <support@submify.com>
#
# This file is part of Submify.
#
# Submify is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Submify is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Submify.  If not, see <http://www.gnu.org/licenses/>.
#
module TopicsHelper
end

app/views/topics/_downvote_button.html.erb
<% if signed_in? %>
  <% if vote = current_user.topic_downvotes.find_by_link_id_and_topic_id(link.id, @topic.id) %>
    <%= form_for vote, :html => { :method => :delete }, remote: true do |f| %>
      <%= button_tag(type: 'submit',class: "undo-butn ") do %>
        <i class="icon-caret-down icon-small"></i>downvoted
      <% end %>
    <% end %>
  <% else %>
    <%= form_for current_user.topic_downvotes.build, url: topic_downvotes_path(link: link, topic: @topic.id), remote: true do |f| %>
      <%= f.hidden_field :user_id %>
      <%= button_tag(type: 'submit',class: "butn ") do %>
        <i class="icon-caret-down icon-small"></i>downvote
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/topics/_follow.html.erb
<%= form_for(current_user.topic_user_relationships.build(topic_id: topic.id), remote: true) do |f| %>
  <div><%= f.hidden_field :topic_id %> </div>
  <%= f.submit "Follow", class: "btn btn-large btn-custom " %>
<% end %>

app/views/topics/_follow_form.html.erb
  <div id="follow_form">
    <% if current_user.topic_following?(topic) %>
      <%= render 'topics/unfollow', topic: topic %>
    <% else %>
      <%= render 'topics/follow', topic: topic %>
    <% end %>
    </div>

app/views/topics/_hovercard.html.erb
<%= image_tag (@topic.avatar.url(:thumb)), class: "topic-pic-hover" %>
<%= link_to @topic.name, @topic, class: "hover-name" %>
  <span class="follow_hover topic-<%= @topic.id %>">  <%= render 'topics/follow_form', topic: @topic if signed_in? %> </span>
  <div class="followers-count hover_stat_topic">
      <%= pluralize(@topic.following_users.count, 'follower') %>
</div>

app/views/topics/_topic.html.erb
<li class="topics_in nostyle">
<div class="follow_button topic-<%= topic.id %>">  <%= render 'topics/follow_form', topic: topic if signed_in? %> </div>
<%= image_tag (topic.avatar.url(:medium)), class: "topic-pic" %>
<%= link_to topic.name, topic, class: 'topic_hover' , data: { hovercard: topic.id } %>
  <% if current_user and current_user.admin? %>
    | <%= link_to "delete", topic, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/topics/_topic_stats.html.erb
<aside> 
  <section>
  <div class="follow_button topic-<%= @topic.id %>">  <%= render 'topics/follow_form', topic: @topic if signed_in? %> </div>
<% cache @topic do %>
<h3>
<%= image_tag (@topic.avatar.url(:medium)), class: "topic-pic" %>
  <%= @topic.name %>
</h3>
<div class="expandable"><%= @topic.description %></div>
<div class="stats_of_topic">
<ul class="breadcrumb">
  <li>
  <%= link_to "Feed" , topic_path(@topic) , class:("active" if @page_tab == "Feed")%><span class="divider">/</span> </li> 
  <li>
  <%= link_to "Edit" , edit_topic_path(@topic) ,class:("active" if @page_tab == "Edit") %> </li>
  <li class="followers-count"> 
  <%= pluralize(@topic.following_users.count, 'follower') %></li>
</ul>
</div>
</div>
</div>
</section>
</aside>
<% end %>

app/views/topics/_unfollow.html.erb
<%= form_for(current_user.topic_user_relationships.find_by_topic_id(topic), html: { method: :delete}, remote:true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/topics/edit.html.erb
<% provide(:title, @topic.name ) %>

<div class="container">
  <div class="span8">
    <% tab "Edit" %>
    <%= render 'topic_stats' %>
    <div class="container">
<div class="span8">
    <h5> Edit Topic </h5>
    <% if  !(@topic.verify) || (current_user.admin? if current_user) %>
      <%= form_for @topic, :html => {:multipart => true}  do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :description %>
        <%= f.text_area :description %>
        <br/>
<%= image_tag (@topic.avatar.url(:thumb)), class: "topic-pic" %>
        <%= f.label :image %>
        <%= f.file_field :avatar %>
        <br/>
        <br/>
        <% if current_user.admin? %>
          Topic verification is  <%= @topic.verify? %>
    | <%= link_to "delete", @topic, method: :delete,
                                  data: { confirm: "You sure?" } %>
          <br/>
          <%= text_field_tag 'verify' %>
        <% end %>
        <%= f.submit "Save changes", class:"btn" %>
      <% end %>
    <% end %>
  </div>
  </div>
</div>
</div>

app/views/topics/followers.html.erb
<% provide(:title, @topic.name) %>
<div class="container">
  <div class="span8">
    <%= render 'topic_stats' %>
    <% if @users.any? %>
      <div class="container">
      <div class="span8">
    <h4>Followers 
      (<%= @users.count %>) </h4>
      <ul class="users">
        <%= render partial: 'users/user', collection: @users %>
      </ul>
      <%= will_paginate @users %>
    </div>
  </div>
    <% end %>
  </div>
</div>

app/views/topics/followers.js.erb
$('.users').append('<%= j (render @users) %>');
<% if @users.next_page %>
  $('.pagination').replaceWith('<%= j (will_paginate(@users)) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/topics/index.html.erb
<div class="container">
  <div class="span8">
    <h3> Follow a topic or create a new one by submitting a link </h3>
    <ol class="topics">

      <%= render @topics %>
      </ol>
      <%= will_paginate @topics %>
  </div>
</div>

app/views/topics/index.js.erb
$('.topics').append('<%= j (render @topics) %>');
<% if @topics.next_page %>
  $('.pagination').replaceWith('<%= j (will_paginate(@topics)) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/topics/show.html.erb
<div class="container">
  <% provide(:title, @topic.name) %>
  <div class="span8">
    <% tab "Feed" %>
    <%= render 'topic_stats' %>
    <div class="container">
      <div class="span8">
        <%= render 'shared/link_form' %>
    <ol class="links">
      <%= render @link_users %>
    </ol>
    <%= will_paginate @link_users%>
  </div>
  </div>
</div>

  <% if @users.any? %>
    <%= render 'shared/user_suggest' %>
  <% end %>

</div>

app/views/topics/show.js.erb
$('.links').append('<%= j (render @links) %>');
<% if @links.next_page %>
  $('.pagination').replaceWith('<%= j (will_paginate(@links)) %>');
<% else %>
  $('.pagination').remove();
<% end %>