config/routes.rb
class AdminConstraint
  def matches?(request)
    return false unless request.session[:user_id]
    user = User.find request.session[:user_id]
    user && user.admin?
  end
end

require 'sidekiq/web'
Submify::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

  resources :password_resets
  resources :votes, only: [:create, :destroy]
  resources :downvotes, only: [:create, :destroy]
  resources :topics, only: [:create, :destroy, :show, :edit ]
  resources :flags, only: [:create, :destroy]
  resources :links, only: [:create, :destroy, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :topic_user_relationships, only: [:create, :destroy]
  resources :links do
    resources :comments, only: [:create, :destroy, :show]
  end
  resources :links do
    member do
      post 'submit', 'unsubmit'
    end
  end
  resources :comments do
    resources :comments, only: [:create, :destroy, :show]
  end
  resources :topics do
    member do
      get :followers, :hovercard
    end
  end
  resources :users do
    member do
      get :following, :followers, :commented, :followed_topics, :hovercard, :notifications
    end
  end
  post 'facebook_create', to: 'users#facebook_create'
  post 'send_again', to: 'sessions#send_again'
  get 'confirmation', to: 'users#confirmation'
  get 'faq', to: 'static_pages#faq'
  match '/admin', to: 'admin#links'
  match '/admin/comments', to: 'admin#comments'
  match '/admin/topics', to: 'admin#topics'
  match '/contact', to: 'static_pages#contact'
  match '/front', to: 'static_pages#front_page'
  match '/auth/:provider/callback', to: 'sessions#fb'
  match '/auth/failure', to: 'sessions#failure'
  match '/signup', to: 'users#new'
  match 'privacy', to: 'static_pages#privacy'
  match 'show_signup', to: 'sessions#show_signup'
  match 'show_signin', to: 'sessions#show_signin'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/autocomplete', to: 'static_pages#autocomplete', as: 'autocomplete'

  match '/autocomplete_topic', to: 'static_pages#autocomplete_topic_name', as: 'autocomplete_topic'
  root to: 'static_pages#home'

end

app/views/admin/_stats.html.erb
<h3> Admin Interface </h3>
<ul class="breadcrumb">
  <li>
  <%= link_to "Links" , admin_path %><span class="divider">/</span> </li> 
  <li>
  <%= link_to "comments" , admin_comments_path %> <span class="divider">/</span> </li>
  <li >
  <%= link_to "topics" , admin_topics_path %> </li>
</ul>

app/views/admin/comments.html.erb
<div class="span8">
  <div class="container-fluid">
    <%= render 'admin/stats' %>
      <ol class="show-commented">
        <%= render @comments %>
      </ol>
      <%= will_paginate @comments %>
  </div>
</div>

app/views/admin/comments.js.erb
$('.show-commented').append('<%= j (render @comments) %>');
<% if @comments.next_page %>
  $('.pagination').replaceWith('<%= j (will_paginate(@comments)) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/admin/links.html.erb
<div class="container-fluid">
  <div class="span8">
     <%= render 'admin/stats' %>
   <% if signed_in? %>
<h4> Links </h4>
      <% if @links %>
        <ol class="links">
    <%= render @links %>
        </ol>
        <%= will_paginate @links %>
      <% else %>
    <h5> No links found </h5>
      <% end %>	
    <% end %>
  </div>  
</div>

app/views/admin/links.js.erb
$('.links').append('<%= j (render @links) %>');
<% if @links.next_page %>
  $('.pagination').replaceWith('<%= j (will_paginate(@links)) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/admin/topics.html.erb
<div class="row-fluid">
  <div class="span8">
     <%= render 'admin/stats' %>
   <ol class="topics">

      <%= render @topics %>
      </ol>
      <%= will_paginate @topics %>
  </div>
</div>

app/views/admin/topics.js.erb
$('.topics').append('<%= j (render @topics) %>');
<% if @topics.next_page %>
  $('.pagination').replaceWith('<%= j (will_paginate(@topics)) %>');
<% else %>
  $('.pagination').remove();
<% end %>