config/routes.rb
class AdminConstraint
  def matches?(request)
    return false unless request.session[:user_id]
    user = User.find request.session[:user_id]
    user && user.admin?
  end
end

require 'sidekiq/web'
Submify::Application.routes.draw do

  mount Sidekiq::Web, at: '/sidekiq', :constraints => AdminConstraint.new

  resources :password_resets
  resources :votes, only: [:create, :destroy]
  resources :downvotes, only: [:create, :destroy]
  resources :topics, only: [:create, :destroy, :show, :edit ]
  resources :flags, only: [:create, :destroy]
  resources :links, only: [:create, :destroy, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :topic_user_relationships, only: [:create, :destroy]
  resources :links do
    resources :comments, only: [:create, :destroy, :show]
  end
  resources :links do
    member do
      post 'submit', 'unsubmit'
    end
  end
  resources :comments do
    resources :comments, only: [:create, :destroy, :show]
  end
  resources :topics do
    member do
      get :followers, :hovercard
    end
  end
  resources :users do
    member do
      get :following, :followers, :commented, :followed_topics, :hovercard, :notifications
    end
  end
  post 'facebook_create', to: 'users#facebook_create'
  post 'send_again', to: 'sessions#send_again'
  get 'confirmation', to: 'users#confirmation'
  get 'faq', to: 'static_pages#faq'
  match '/admin', to: 'admin#links'
  match '/admin/comments', to: 'admin#comments'
  match '/admin/topics', to: 'admin#topics'
  match '/contact', to: 'static_pages#contact'
  match '/front', to: 'static_pages#front_page'
  match '/auth/:provider/callback', to: 'sessions#fb'
  match '/auth/failure', to: 'sessions#failure'
  match '/signup', to: 'users#new'
  match 'privacy', to: 'static_pages#privacy'
  match 'show_signup', to: 'sessions#show_signup'
  match 'show_signin', to: 'sessions#show_signin'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/autocomplete', to: 'static_pages#autocomplete', as: 'autocomplete'

  match '/autocomplete_topic', to: 'static_pages#autocomplete_topic_name', as: 'autocomplete_topic'
  root to: 'static_pages#home'

end

app/views/shared/_comment_form.html.erb
<% if signed_in? %>
  <% comment = @link.id and value =1 if @link %>
  <% comment = @comment.id and value = 0 if @comment %>
  <%= form_for :comment, url: comments_path(comment_id: comment, val: value), remote: true, id: "comment_form"  do |f| %>
  <div class="field_comment">
    <% if @link %>
    <%= f.text_area :body, placeholder: "Add a comment", id: "comment_text", value: ""%>
    <br/>
    <%= f.submit "Comment", class: "btn btn-small"%>
    <% else %>
    <%= f.text_area :body, placeholder: "Add a reply", id: "comment_text", value: ""%>
    <br/>
    <%= f.submit "Reply", class: "btn btn-small"%>
    <% end %>
  </div>
<% end %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
      
        <% if @user.errors.count >= 5 %>
        <li> Fields cannot be empty </li>
        
       <% else %>

         <% @user.errors.full_messages.each do |msg| %>
            
            <% if not @user.errors[:password_digest].empty? %>
            
            <% else %>
              
              <li> <%= msg %> </li>
            
            <% end %>
          
          <% end %>
        
        <% end %>
    </ul>
  
  </div>
<% end %>

app/views/shared/_feed_item.html.erb
<div class="feed_contain">
<%= render 'links/link', link: feed_item %>
<ol class="full_comments"> 
  <div class="span8">
    <div class="span6 ">
      <!--
         -<%= render partial: 'comments/comment', collection: feed_item.following_comments(current_user) %>
         -->
      <br/>
    </div>
    
  </div>
</ol>
</div>

app/views/shared/_link_form.html.erb
<% if signed_in? %>
<% name , val = nil %>
<% name = @topic.name and val= @topic.id if @topic %>
<%= form_for @link , remote: true do |f| %>
  <div class="field">
    <%= f.text_area :url_link, placeholder: "Submit the best thing(url link) you saw on the Internet today ", id: "complete_url"%>

    <%= text_field_tag 'topic_name', name , class: 'link-topic-tag', placeholder: "Topic name(only one)" %>
    <%= text_area_tag 'comment_body', nil, placeholder: "Add a comment", id: "link_c_text"%>
    <br/>
   <%= hidden_field_tag 'topic_val', val  %>
    <%= f.submit "Submit", class: "btn btn-small gif-load", id: "submit_button"%>
  </div>
<% end %>

<% end %>

app/views/shared/_link_form_new.html.erb
<div class="intro_box">
<% if signed_in? %>
  <% name , val = nil %>
  <!--
     -<span class="head_intro"><h3> Start sharing links with the appropriate topic community </h3></span>
     -->

<%= form_for @link do |f| %>
  <div class="field">
    <br/>
    <span class="link_explain">1) Submit a link in the box eg: http://example.com/food.html </span>
    <br/>
    <br/>
    <%= f.text_area :url_link, class: 'new_user_text', placeholder: "Submit the best thing you saw on the Internet today "%>
    <br/>
    <br/>
    <span class="link_explain">2) Choose one suitable topic from autocomplete or just type to create a new one. eg. Food </h5>
  </span>
  <br/>
  <br/>
    <%= text_field_tag 'topic_name', name , class: 'link-topic', placeholder: "Topic name(only one)" %>
   <%= hidden_field_tag 'topic_val', val  %>
   <br/>
   <br/>
   <span class="link_explain">3)  Give your thoughts about the link 
  </span>
  <br/>
    <%= text_area_tag 'comment_body', nil, placeholder: "Add a comment"%>
    <br/>
   <%= f.submit "Submit", class: "btn btn-small gif-load"%>
   <br/>
   <br/>

   <span class="link_explain"> The submitted link will reach the topic followers and to your followers. Start submitting links </span>
  </div>
<% end %>

<% end %>
</div>

app/views/shared/_show_topics_nav.html.erb
<% cache ["topics", current_user ] do %>
  <li><%= link_to "Front Page", front_path %></li>
  <li><%= link_to "Discover", topics_path %> </li>
            <li class="divider"></li>
            <% current_user.followed_topics.each do |topic| %>
              <li> <%= link_to topic.name, topic_path(topic) %> </li>
            <% end %>
        <% end %>

app/views/shared/_sign_in_fixed.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4">
      <div class="well sidebar-nav sidebar-nav-fixed">
        <div class="make_session">
          <%= render 'sessions/login_page' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sign_up.html.erb
    <h4> Sign up </h4>
    <br/>

    <%= form_for @user do |f| %>

      <%= f.label :name, 'Full Name' %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large" %>
    <% end %>
    <p> Existing user? <%= link_to "Sign in now", show_signin_path, remote: true %> </p>

app/views/shared/_social_media.html.erb
<div class="container-fluid">
  <div class="row-fluid social_box">

  <span class="s_media"><%= link_to image_tag('Facebook.png'), "http://facebook.com/Submify"%></span>

  <span class="s_media"><%= link_to image_tag('Googleplus.png'), "https://plus.google.com/107604214559033316293" %></span>
  <span> <%= link_to image_tag('Twitter.png'), "http://twitter.com/submify" %></span>
  </div>
</div>

app/views/shared/_stats.html.erb
<ul class="breadcrumb">
  <li class="links_user">
  <%= link_to pluralize(@user.link_users_count, 'link') , user_path(@user) %><span class="divider">/</span> </li> 
  <li class="comments_user">
  <%= link_to pluralize(@user.comments_count, 'comment') , commented_user_path(@user) %> <span class="divider">/</span> </li>
  <li class="followers_user">
  <%= link_to pluralize(@user.relationships_count, 'follower') , followers_user_path(@user)%> </li>
</ul>

app/views/shared/_topics_sidebar.html.erb
<ul class="topics_tab">
  <% Topic.limit(25).each do |topic| %>
  <li class="topic_front"><%= link_to topic.name, topic %></li>
  <% end %>
  <%= link_to "More", topics_path, class: "topic_front"%>
</ul>

app/views/shared/_topics_suggest.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4">
      <div class="well sidebar-nav sidebar-nav-fixed sidebar-rel">
        <h4> Suggested Topics </h4>
        <ul class="users">
          <% @topics.each do |topic| %>
            <li>
            <%= image_tag (topic.avatar.url(:medium)), class: "gravatar" %>
            <%= link_to topic.name, topic, class: 'topic_hover', data: {hovercard: topic.id} %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_user_suggest.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span4">
      <div class="well sidebar-nav sidebar-nav-fixed sidebar-rel">
        <h4> Followers </h4>
        <ul class="users">
          <% @users.each do |user| %>
            <li>
            <%= image_tag (user.avatar.url(:medium)), class: "gravatar" %>
            <%= link_to user.name, user, class: 'profile_hover', data: {hovercard: user.id} %>
            </li>
          <% end %>
        </ul>
        <%= link_to "See more", followers_topic_path %>
      </div>
    </div>
  </div>


</div>